services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/MARIADB

volumes:
  mariadb_data:
